### ISSUE TITLE
Code Update

### ISSUE THREAD

**Issue by javaskater** [oreillymedia/programmers_guide_to_drupal#1]
I bought the book already 6 month ago... and still no update ...
The examples are 1 year old at least and since Drupal 8 did seriously evolve !

- I personally build a [module to import (through a drush command) dayHikes out of a csv file](https://github.com/javaskater/rif_imports)!

- And I was confronted to many deprecated features

I am waiting impatiently for the next update !
When should it come ???

**Comment by jhodgdon-drp** [comment]
Sorry about that! I actually have plans to make an update to the book and code, starting next week.

**Comment by jhodgdon-drp** [comment]
I've just made a commit to update the code/tests so that the tests pass in Drupal 8.3.x.

I also added a test to help me locate deprecated classes and functions that are mentioned in the code and in the text of the book. Here's the list that I came up with -- I plan to update the code that uses of all of them in the next two weeks. If you know of anything I missed, please post a comment here. Thanks!

Interface \Drupal\Core\Entity\EntityManagerInterface [and related classes]
Class \Drupal\Component\Utility\SafeMarkup
Class \Drupal\simpletest\KernelTestBase
Method \Drupal::l()

Functions [some of these are only partially deprecated, but they need to at least be looked at]:

check_url()
drupal_render()
db_add_field()
db_change_field()
db_create_table()
db_query()
db_select()
check_markup()
t()

**Comment by jhodgdon-drp** [comment]
I've completed the updates. I believe that all of the code is now free of deprecated classes/methods/etc.

I'll go ahead and close this issue, but if you find anything that you think needs to be updated, please let me know by creating another issue with the specifics.

Thanks for creating this issue, by the way -- I had been planning for a while to do these updates, and I needed the motivation (obviously). It was too long of a delay... I think that the Drupal 8 API is more stable now and hopefully large changes will not be necessary for Drupal 8.4, 8.5, etc. But, in any case, I'll try to keep up with it better.

**Comment by javaskater** [comment]
Thanks a lot for your remarks, I will try the updated code. Your explanations / comments are always of really good value !!

That book you started is a level higher than any other one that try to  introduce you in the world of  the programming / theming for Drupal8. 

I know the actual difficulty lies in the unstable API and the lack of really stable contributed modules ...

**_Drupal Programing_** is  source of inspiration for the Drupal 8 trainings I will have to start here in France (see my [french wiki](http://wiki.jpmena.eu/index.php?title=Accueil#Cas_du_d.C3.A9veloppement_Symfony.2FDrupal8))

Please continue writing it !
